#ifndef _AST_H
#define _AST_H

enum nodetype {
	AST_ADECL,
	AST_ADIRDECL,
	AST_ARGLIST,
	AST_ASSIGN,
	AST_ATYPE,
	AST_AUTOKW,
	AST_BINARY,
	AST_BLOCK,
	AST_BLOCKLIST,
	AST_BODY,
	AST_BREAK,
	AST_C99INIT,
	AST_CALL,
	AST_CASED,
	AST_CAST,
	AST_CONDITIONAL,
	AST_CONTINUE,
	AST_DECL,
	AST_DIRDECL,
	AST_DECLLIST,
	AST_DECLSPEC,
	AST_DECLSTMT,
	AST_DEFAULTED,
	AST_DEREF,
	AST_DESIGLIST,
	AST_DESIGNATION,
	AST_DESIGNATOR,
	AST_DO,
	AST_ENUM,
	AST_ENUMLIST,
	AST_ENUMVAL,
	AST_EXPRLIST,
	AST_EXTERNKW,
	AST_FILE,
	AST_FOR,
	AST_FUNCSPEC,
	AST_FUNCTION,
	AST_GETATTR,
	AST_GETINDEX,
	AST_GOTO,
	AST_IDENTIFIER,
	AST_IDLIST,
	AST_IF,
	AST_INIT,
	AST_INITIALIZER,
	AST_INITIALIZERLIST,
	AST_INITLIST,
	AST_INTEGER,
	AST_LABELED,
	AST_MACRO,
	AST_PARAMDECL,
	AST_PARAMLIST,
	AST_PTR,
	AST_REGISTERKW,
	AST_RETURN,
	AST_SIZEOF,
	AST_STATICKW,
	AST_STMT,
	AST_STRING,
	AST_STRUCT,
	AST_STRUCTBITS,
	AST_STRUCTDECL,
	AST_STRUCTDECLLIST,
	AST_STRUCTKW,
	AST_STRUCTLIST,
	AST_STRUCTQUALLIST,
	AST_STRUCTSTMT,
	AST_SWITCH,
	AST_TYPE,
	AST_TYPEDEFKW,
	AST_TYPENAME,
	AST_TYPEQUAL,
	AST_TYPEQUALLIST,
	AST_UNARY,
	AST_UNARYOP,
	AST_UNIONKW,
	AST_WHILE
};

enum decltype {
	DECL_ID,
	DECL_INPARENS,
	DECL_PARENS,
	DECL_PARENS_TYPE,
	DECL_PARENS_ID,
	DECL_BRACS,
	DECL_BRACS_TYPE,
	DECL_BRACS_ASSIGN,
	DECL_BRACS_BOTH,
	DECL_BRACS_STATIC_ASSIGN,
	DECL_BRACS_STATIC_BOTH,
	DECL_BRACS_BOTH_STATIC,
	DECL_BRACS_STAR,
	DECL_BRACS_TYPE_STAR
};

struct node {
	enum nodetype type;
	long start, end;
	struct node **children;
	struct node *parent;
	int count;
	void *data;
};

struct node *parse(char *filename);
void node_free(struct node *node);
struct node *node_find(struct node *node, long offset);
void node_walk(struct node *, int (*) (struct node *, void *), void *);
int node_cmp(struct node *n1, struct node *n2);
struct node *declarator_name(struct node *node);

#endif
